owner: adsblol # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository
user-agent: ADSB.lol Status Page
sites:
- name: adsb.lol
  url: https://adsb.lol
- name: globe.adsb.lol
  url: https://globe.adsb.lol
- name: mapproxy.adsb.lol
  url: https://mapproxy.adsb.lol/tiles/openaip/openaip_grid/12/2101/1346.png
- name: api.adsb.lol
  url: https://api.adsb.lol/metrics
  headers:
    - "User-Agent: ADSB.lol Status Page"
- name: feed.adsb.lol:1337
  url: feed.adsb.lol
  check: tcp-ping
  port: 1337
- name: feed.adsb.lol:1338
  url: feed.adsb.lol
  check: tcp-ping
  port: 1338
- name: feed.adsb.lol:30004
  url: feed.adsb.lol
  check: tcp-ping
  port: 30004
- name: feed.adsb.lol:30005
  url: feed.adsb.lol
  check: tcp-ping
  port: 30005
- name: feed.adsb.lol:31090
  url: feed.adsb.lol
  check: tcp-ping
  port: 31090
- name: adsb.im
  url: https://adsb.im
  assignees:
    - dirkhh 
- name: my.adsb.im
  url: https://my.adsb.im
  assignees:
    - dirkhh 

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.adsb.lol
  # baseUrl: /your-repo-name
  logoUrl: https://avatars.githubusercontent.com/u/123735118?s=200&v=4
  name: ADSB.lol Status
  introTitle: "ADSB.lol Status"
  introMessage: Status page for ADSB.lol
  navbar:
  - title: Status
    href: /
  - title: GitHub
    href: https://github.com/adsblol/status

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
